application: photobout-test
version: 1
runtime: python27
api_version: 1
threadsafe: false

builtins:
- remote_api: on
- deferred: on
- appstats: on

handlers:
- url: /users/.*
  script: handlers.web.users.application

- url: /bouts/.*
  script: handlers.web.bouts.application

libraries:
- name: django
  version: "1.4"
