application: photobout-test
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /users/.*
  script: handlers.web.users.application

- url: /bouts/.*
  script: handlers.web.bouts.application
